INSERT INTO `queren` VALUES (27, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO `queren` VALUES (28, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO `queren` VALUES (29, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO `queren` VALUES (30, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO `queren` VALUES (31, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO `queren` VALUES (32, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO `queren` VALUES (33, '我11', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO `queren` VALUES (34, '薛某', '110', '0015', '東京都', '台東区', '東上野', 'セツ', 'セツ', 'セツ', 'wetech', '我', '我', '1234567890123', '我', '18698604369', '12345678901', 'setsu6666@gmail.com', 'setsu6666@gmail.com', NULL);
INSERT INTO `queren` VALUES (35, '薛某', '110', '0015', '東京都', '台東区', '東上野', 'セツ', 'セツ', 'セツ', 'wetech', '我', '我', '1234567890123', '我', '18698604369', '12345678901', 'setsu6666@gmail.com', 'setsu6666@gmail.com', '2023-6-9 18:13:22');
